---
- name: Setup SSH
  vars_files:
    - ../vault/vars.yaml
  hosts: all
  tasks:
    - name: Set authorized key
      authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', pub_key_loc) }}"
- name: Setup static ip
  vars_files:
    - ../vault/vars.yaml
  hosts: all
  tasks:
    - name: Set the current MAC address
      set_fact:
        pi_mac_address: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
    - name: Set variables based on MAC address
      set_fact:
        pi_hostname: "{{ mac_address_mapping[pi_mac_address].name }}"
        pi_ip_address: "{{ mac_address_mapping[pi_mac_address].ip }}"
    - name: Register router ip
      shell: ip r | grep default | awk '/default/ {print $3}'
      register: router_ip
    - name: Register default network
      shell: ip r | grep default | awk '/default/ {print $5}'
      register: default_network
    - name: Insert/Update static ip in dhcpcd.conf
      become: true
      when: (pi_ip_address is defined) and (pi_ip_address|length > 0)
      blockinfile:
        path: /etc/dhcpcd.conf
        marker: "### {mark} ANSIBLE MANAGED BLOCK"
        block: |
          interface {{ default_network.stdout }}
          static ip_address={{ pi_ip_address }}/24
          static routers={{ router_ip.stdout }}
          static domain_name_servers={{ router_ip.stdout }} {{ dns_nameservers | join(' ') }}
    - name: Reboot the machine
      become: true
      reboot:
