---
- name: Base setup
  hosts: all
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
    - name: Install Vim
      become: true
      apt:
        name: vim
        state: present
        install_recommends: true
